# TUGAS 2

## **A. DISKRITISASI**
> *Diskritisasi adalah kegiatan yang dilakukan untuk mengubah niai data numerik menjadi kategorial*

> **## 1. Equal-width**



>>*Equal-width adalah algoritma untuk membagi rentang dari X menjadi k interval dengan ukuran lebar yang sama*

In [1]:
#Datasets iris
import pandas as pd
import numpy as np
import statistics as st
pd.options.mode.chained_assignment=None

url_iris='https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
data_iris=pd.read_csv(url_iris)
data_iris

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [2]:
data_sepal_lengthEW =  data_iris[["sepal.length"]] #data frame
data_sepal_widthEW =  data_iris[["sepal.width"]]
data_petal_lengthEW =  data_iris[["petal.length"]]
data_petal_widthEW =  data_iris[["petal.width"]]

Method cut digunakan untuk mencari interval menggunakan metode equal-width interval

In [3]:
def cut(col,k):
  intervals=pd.cut(data_iris[col],k).value_counts().index.to_list() 
  return [[interval.left,interval.right] for interval in intervals]

In [4]:
def toCategory(list_interval,col):
  #get length interval
  length = len(list_interval)

  #sorting interval
  sort_interval=np.sort(list_interval,axis=0)
  #get category from interval
  categories = np.array([chr(65+i) for i in range(length)])[:,None]
  #combine into interval data
  intervals = np.hstack((sort_interval,categories))

  #operate all data
  newCol=[]
  for i, row in data_iris.iterrows():
    data=row[col]
    for interval in intervals:
      if data >= interval[0].astype(float) and data <= interval[1].astype(float):
        newCol.append(interval[2])
        break

  #return new column category
  return np.array(newCol,dtype=str)

Mencari interval sebagai contoh disini dibagi menjadi 3 bagian

In [17]:
interval_sepal_length =  cut("sepal.length",3) #data frame
interval_sepal_width =  cut("sepal.width",3)
interval_petal_length =  cut("petal.length",3)
interval_petal_width =  cut("petal.width",3)

print("interval_sepal.length :",interval_sepal_length)
print("interval_sepal.width :",interval_sepal_width)
print("interval_petal.length :",interval_petal_length)
print("interval_petal.width :",interval_petal_width)

interval_sepal.length : [[5.5, 6.7], [4.296, 5.5], [6.7, 7.9]]
interval_sepal.width : [[2.8, 3.6], [1.998, 2.8], [3.6, 4.4]]
interval_petal.length : [[2.967, 4.933], [0.994, 2.967], [4.933, 6.9]]
interval_petal.width : [[0.9, 1.7], [0.0976, 0.9], [1.7, 2.5]]

Tampilan hasil dari pembagian category

In [10]:
data_sepal_lengthEW["category"] = toCategory(interval_sepal_length,"sepal.length")
data_sepal_widthEW["category"] = toCategory(interval_sepal_width,"sepal.width")
data_petal_lengthEW["category"] = toCategory(interval_petal_length,"petal.length")
data_petal_widthEW["category"] = toCategory(interval_petal_width,"petal.width")

display(data_sepal_lengthEW)
display(data_sepal_widthEW)
display(data_petal_lengthEW)
display(data_petal_widthEW)

     sepal.length category
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        B
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

     sepal.width category
0            3.5        B
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        B
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        B
149          3.0        B

[150 rows x 2 columns]

     petal.length category
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     petal.width category
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        C
146          1.9        C
147          2.0        C
148          2.3        C
149          1.8        C

[150 rows x 2 columns]

In [12]:
equalWidth = pd.DataFrame([])
equalWidth["sepal.length"] = data_iris["sepal.length"]
equalWidth['SL.eqWcategory'] = data_sepal_lengthEW["category"]

equalWidth["petal.length"] = data_iris["petal.length"]
equalWidth["PL.eqWcategory"] = data_sepal_lengthEW["category"]

equalWidth["sepal.width"] = data_iris["sepal.width"]
equalWidth["SW.eqWcategory"] = data_sepal_widthEW["category"]

equalWidth["petal.width"] = data_iris["petal.width"]
equalWidth["PW.eqWcategory"] = data_petal_widthEW["category"]

equalWidth["variety"] = data_iris[["variety"]]

equalWidth

,sepal.length,SL.eqWcategory,petal.length,PL.eqWcategory,sepal.width,SW.eqWcategory,petal.width,PW.eqWcategory,variety
0,5.1,A,1.4,A,3.5,B,0.2,A,Setosa
1,4.9,A,1.4,A,3.0,B,0.2,A,Setosa
2,4.7,A,1.3,A,3.2,B,0.2,A,Setosa
3,4.6,A,1.5,A,3.1,B,0.2,A,Setosa
4,5.0,A,1.4,A,3.6,B,0.2,A,Setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,B,5.2,B,3.0,B,2.3,C,Virginica
146,6.3,B,5.0,B,2.5,A,1.9,C,Virginica
147,6.5,B,5.2,B,3.0,B,2.0,C,Virginica
148,6.2,B,5.4,B,3.4,B,2.3,C,Virginica
149,5.9,B,5.1,B,3.0,B,1.8,C,Virginica

> ## 2. Equal-Frekuensi Interval



>>*Equal frekuensi interval adalah algoritma untuk membagi rentang dari X menjadi rentang-rentang yang berisi nilai data yang kurang lebih nilainya sama*

In [19]:
data_sepal_lengthEF = data_iris[["sepal.length"]]
data_sepal_widthEF = data_iris[["sepal.width"]]
data_petal_lengthEF = data_iris[["petal.length"]]
data_petal_widthEF = data_iris[["petal.width"]]

pandas menyediakan qcut untuk mencari nilai interval dari Equal-Frequency Intervals

In [21]:
def qcut(col, k):
  intervals = pd.qcut(data_iris[col], k).value_counts().index.to_list()
  return [[interval.left, interval.right] for interval in intervals]

Mencari interval sebagai contoh disini dibagi menjadi 3 bagian

In [24]:
interval_sepal_lengthEF =  qcut("sepal.length",3) #data frame
interval_sepal_widthEF =  qcut("sepal.width",3)
interval_petal_lengthEF =  qcut("petal.length",3)
interval_petal_widthEF =  qcut("petal.width",3)

print("interval_sepal.length :",interval_sepal_lengthEF)
print("interval_sepal.width :",interval_sepal_widthEF)
print("interval_petal.length :",interval_petal_lengthEF)
print("interval_petal.width :",interval_petal_widthEF)

interval_sepal.length : [[5.4, 6.3], [4.2989999999999995, 5.4], [6.3, 7.9]]
interval_sepal.width : [[1.999, 2.9], [2.9, 3.2], [3.2, 4.4]]
interval_petal.length : [[2.633, 4.9], [0.999, 2.633], [4.9, 6.9]]
interval_petal.width : [[0.867, 1.6], [0.099, 0.867], [1.6, 2.5]]

Menampilkan hasil pembagian category

In [25]:
data_sepal_lengthEF["category"] = toCategory(interval_sepal_length,"sepal.length")
data_sepal_widthEF["category"] = toCategory(interval_sepal_width,"sepal.width")
data_petal_lengthEF["category"] = toCategory(interval_petal_length,"petal.length")
data_petal_widthEF["category"] = toCategory(interval_petal_width,"petal.width")

display(data_sepal_lengthEF)
display(data_sepal_widthEF)
display(data_petal_lengthEF)
display(data_petal_widthEF)

     sepal.length category
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        C
146           6.3        B
147           6.5        C
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

     sepal.width category
0            3.5        C
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        C
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        C
149          3.0        B

[150 rows x 2 columns]

     petal.length category
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     petal.width category
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        C
146          1.9        C
147          2.0        C
148          2.3        C
149          1.8        C

[150 rows x 2 columns]

In [27]:
equalFrequency = pd.DataFrame([])
equalFrequency["sepal.length"] = data_iris["sepal.length"]
equalFrequency['SL.Freqcategory'] = data_sepal_lengthEF["category"]

equalFrequency["petal.length"] = data_iris["petal.length"]
equalFrequency["PL.Freqcategory"] = data_sepal_lengthEF["category"]

equalFrequency["sepal.width"] = data_iris["sepal.width"]
equalFrequency["SW.Freqcategory"] = data_sepal_widthEF["category"]

equalFrequency["petal.width"] = data_iris["petal.width"]
equalFrequency["PW.Freqcategory"] = data_petal_widthEF["category"]

equalFrequency["variety"] = data_iris[["variety"]]
equalFrequency

,sepal.length,SL.Freqcategory,petal.length,PL.Freqcategory,sepal.width,SW.Freqcategory,petal.width,PW.Freqcategory,variety
0,5.1,A,1.4,A,3.5,C,0.2,A,Setosa
1,4.9,A,1.4,A,3.0,B,0.2,A,Setosa
2,4.7,A,1.3,A,3.2,B,0.2,A,Setosa
3,4.6,A,1.5,A,3.1,B,0.2,A,Setosa
4,5.0,A,1.4,A,3.6,C,0.2,A,Setosa
...,...,...,...,...,...,...,...,...,...
145,6.7,C,5.2,C,3.0,B,2.3,C,Virginica
146,6.3,B,5.0,B,2.5,A,1.9,C,Virginica
147,6.5,C,5.2,C,3.0,B,2.0,C,Virginica
148,6.2,B,5.4,B,3.4,C,2.3,C,Virginica
149,5.9,B,5.1,B,3.0,B,1.8,C,Virginica

> ## 3. Entropy

>*Entropy adalah nilai informasi yang menyatakan ukuran ketidakpastian(impurity) dari attribut dari suatu kumpulan obyek data dalam satuan bit.*

>*   Rumus Entropy:



$$Entropy (D_{1}) = -\sum_{i=1}^{m} Pi \log_{2} Pi$$

>*   Rumus Gain:



$$Gain(E_{new}) = E_{initial} - E_{new}$$
>*   Rumus Info:



$$Info_{A}(D) = \frac{|D_{_{1}}|}{|D|} Entropy(D_{1}) + \frac{|D_{2}|}{|D|} Entropy(D_{2})$$

Membuat sample data untuk di analisis

In [28]:
sample = data_iris[["sepal.length"]]
sample.describe()

       sepal.length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

Membuat category random untuk semua data

In [29]:
np.random.seed(0)
sample["category"] = np.where(np.random.choice(2,sample.shape[0]) < 1,"A","B")
sample

     sepal.length category
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

Membuat fungsi GetOverollCategory (keseluruhan) yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [30]:
def GetOverollCategory(col):
  group = sample.loc[:, :].groupby("category").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a,b,a+b)

Fungsi splitter digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [31]:
def splitter(value, col):
  #get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  #calculate into category for each data
  less_group = less.loc[:, :].groupby("category").count()
  greater_group = greater.loc[:, :].groupby("category").count()

  #get value based on category
  less_category_A = less_group.loc["A",col]
  less_category_B = less_group.loc["B",col]
  greater_category_A = greater_group.loc["A",col]
  greater_category_B = greater_group.loc["B",col]

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Buat fungsi entropy untuk mencari nilai entropy

In [32]:
def entropy (d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
  return np.sum([r1, r2]) * -1

Membuat fungsi info dan gain

In [34]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

Fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru

In [33]:
def gain(Einitial, Enew):
  return Einitial - Enew

Membuat D initial

In [35]:
D = GetOverollCategory("sepal.length")
entropy_d = entropy(D)
print(D)
print(entropy_d)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk menari informasi yang terbaik

### *Split 1 : 4.4*

In [36]:
split1 = splitter(4.4, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.003488151753460178

### *Split 2 : 5.5*

In [37]:
split2 = splitter(5.5, "sepal.length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.012302155146638905

### *Split 3 : 7.0*

In [38]:
split3 = splitter(7.0, "sepal.length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0005490214732508658

Split terbaik yaitu split 3 yang memberikan keuntungan informasi sebesar 0.0005490214732508658 karena yang paling rendah